### ISSUE TITLE
Image on dialog gets broken - location page

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#34]
When adding an image to each article inside location page, the image gets broken. 
In the final form, each article on that page should have a picture. 

![image](https://user-images.githubusercontent.com/26923359/33525590-7b0556e0-d83b-11e7-96c0-5bb2a2a1c7ff.png)

**Comment by MeanEYE** [comment]
Design never showed images in location information. Hence omission on our part with images. Why is this the case now? It's easily fixed but I need to know if this is actually necessary addition or just client thinks it's cool now, but didn't think about it last time we did the design.

In other words, this is not a bug this is new feature we have to add now since it wasn't on design.

**Comment by talovdat** [comment]
Another design that fell between the chairs, the client showed me conversations between her and Misha and Hanan in which she asked for this design a few months ago. Hanan confirmed.

**Comment by MeanEYE** [comment]
And no one decided to notify me, which means it didn't happen. Okay, this fix needs to be implemented then.

**Comment by MeanEYE** [comment]
In fact @talovdat can you check with client if it would be okay to move locations to separate pages instead of popups?

**Comment by talovdat** [comment]
Hanan say's that it's up to you. He prefer's popups, but if that is a problematic subject then do what you think is best.

**Comment by MeanEYE** [comment]
Well, think about it this way. If we have 50 locations, that's 50 different articles, with the same amount of images. So all of those have to be loaded and only some will be displayed. 

However, we can make it look identical as popup, just load the content when needed.

**Comment by MeanEYE** [comment]
@VladimirWebDev make additional section for individual location. We are not going to handle them as popups, but they will look like popups on those separate pages.

**Comment by MeanEYE** [comment]
@VladimirWebDev this one is paused for the moment.

**Comment by VladimirWebDev** [comment]
@MeanEYE If I am correct this issue is not valid anymore, since whole structure of location page is changed. However this issue [https://github.com/Way2CU/Yuni-Site/issues/59](https://github.com/Way2CU/Yuni-Site/issues/59) is somewhat connected because for now there is only text on concrete locations pages. If something else is added we need to add style, since I can't predict what can be added (images or else), maybe some, close to final, definition of how pages should look like.

**Comment by MeanEYE** [comment]
Not valid. Close
