### ISSUE TITLE
Footer text edting

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#61]
![image](https://user-images.githubusercontent.com/26923359/35361981-2bee2172-016c-11e8-8a2f-18395ffcdb68.png)

Increase A to the size of B
then C goes under A

**Comment by MeanEYE** [comment]
B is a logo they gave us. And more to the point it's a typography type logo, designed to be in specific relation to the rest of the text surrounding it. Am not sure this is a good idea, besides text is inside of the image so we'd need Michael for that.

**Comment by talovdat** [comment]
If they will provide us with a new logo for that matter, will it help?

**Comment by MeanEYE** [comment]
You are not the designer. So there's no need for you to play with this especially when it comes to image optimization and other stuff. I simply need to know why it needs to be bigger now and was okay until this point.

**Comment by talovdat** [comment]
We have no designer and I'm okay with working on photoshop. 
Hanan tried to convince her to move on but apparently, it's a copyrights matter.

**Comment by MeanEYE** [comment]
It's a copyright matter for text to be bigger? I highly doubt so. Also, this is not Photoshop it's vector graphics and this is not a question of whether you are okay with working in graphics design programs or not it's a question of quality and experience.

**Comment by talovdat** [comment]
If it's too much to deal with, and not recommended at all, I'll talk the client out of it.

**Comment by MeanEYE** [comment]
It's not the question of how much. It's the question of whether it's needed or not. You said it's a "copyright issue" and it's not. Copyright is something completely different. If they want it bigger simply because they feel like it needs to be bigger, then they should provide us with bigger logo. Even when Michael was working with us we weren't touching logos because client always complains about something there and it takes too much time to get anything right.

When we asked them to provide branding information, logos included, they should have provided one that fits. If they want a different one, then they should provide a different one. I am not going to have my developers sit around and mess with images they should have prepared. And it's also not your job to mess around with _their logo_.

**Comment by talovdat** [comment]
Fair enough.
