### ISSUE TITLE
Make links on sign up page manageable

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Yuni-Site#90]
All the links on the page registration/signup should be manageable through the backend. 
Client needs the ability to add, remove and order those links.
For example, first three links are not manageable through the backend office.
![image](https://user-images.githubusercontent.com/26923359/37343471-557a21ec-26d0-11e8-8612-e2c484c6ad92.png)

**Comment by VladimirWebDev** [comment]
Those three first links are not hosted by us thus were hard-coded. I've tested two options to solve this. One option is to add one more article where they can add, remove and order links just like in other articles. Second option is to use Links module with group of links where they also can add, remove and order links. However since there will be one more module call I need to now which set of links comes first. @MeanEYE I need opinion.

**Comment by MeanEYE** [comment]
Both solutions are good. However, I'll wait for @talovdat's consult on this one before committing to any solution. Solution with articles sounds more intuitive as adding additional module to this site could get overwhelming for the client.

**Comment by MeanEYE** [comment]
Articles it is.

**Comment by VladimirWebDev** [comment]
@talovdat There is standalone article created on admin with title External links sign up page, where are those three links added. They can add, remove arrange them from that article. When new changes deployed it will be manageable.
